// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_mHJgJfBr6yk1WLIU_AT75HsJBOWJaWA',
    appId: '1:302478229500:web:92243b38d4b853bf973c79',
    messagingSenderId: '302478229500',
    projectId: 'expense-tracker-c9d9c',
    authDomain: 'expense-tracker-c9d9c.firebaseapp.com',
    storageBucket: 'expense-tracker-c9d9c.appspot.com',
    measurementId: 'G-GZL2EJ2WYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiNbLBKCoZAmAjkMwOLBKQ3nvnPGERDto',
    appId: '1:302478229500:android:52917e1f83f1bc12973c79',
    messagingSenderId: '302478229500',
    projectId: 'expense-tracker-c9d9c',
    storageBucket: 'expense-tracker-c9d9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB0Gm-n5HyNofGOd_LdNCobHSqiJTyHk8',
    appId: '1:302478229500:ios:b38a80fa10b5d15c973c79',
    messagingSenderId: '302478229500',
    projectId: 'expense-tracker-c9d9c',
    storageBucket: 'expense-tracker-c9d9c.appspot.com',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB0Gm-n5HyNofGOd_LdNCobHSqiJTyHk8',
    appId: '1:302478229500:ios:b38a80fa10b5d15c973c79',
    messagingSenderId: '302478229500',
    projectId: 'expense-tracker-c9d9c',
    storageBucket: 'expense-tracker-c9d9c.appspot.com',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_mHJgJfBr6yk1WLIU_AT75HsJBOWJaWA',
    appId: '1:302478229500:web:3f0bb13b682303bc973c79',
    messagingSenderId: '302478229500',
    projectId: 'expense-tracker-c9d9c',
    authDomain: 'expense-tracker-c9d9c.firebaseapp.com',
    storageBucket: 'expense-tracker-c9d9c.appspot.com',
    measurementId: 'G-GW1VDJ7P1R',
  );
}
